-- -----------------------------------------------------
-- Tabla: Usuarios
-- -----------------------------------------------------
CREATE TABLE Usuarios (
  usuario_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  email VARCHAR2(100) NOT NULL UNIQUE,
  password_hash VARCHAR2(255) NOT NULL,
  tipo_usuario VARCHAR2(20) NOT NULL,
  nombre VARCHAR2(100) NOT NULL,
  apellido VARCHAR2(100),
  telefono VARCHAR2(20),
  fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chk_tipo_usuario CHECK (tipo_usuario IN ('cliente', 'gerente', 'admin_gerente'))
);

-- -----------------------------------------------------
-- Tabla: Clientes
-- -----------------------------------------------------
CREATE TABLE Clientes (
  cliente_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  usuario_id NUMBER NOT NULL UNIQUE,
  direccion_facturacion CLOB,
  CONSTRAINT fk_cliente_usuario
    FOREIGN KEY (usuario_id)
    REFERENCES Usuarios (usuario_id)
    ON DELETE CASCADE
);

-- -----------------------------------------------------
-- Tabla: Gerentes
-- -----------------------------------------------------
CREATE TABLE Gerentes (
  gerente_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  usuario_id NUMBER NOT NULL UNIQUE,
  estatus VARCHAR2(20) DEFAULT 'activo' NOT NULL,
  CONSTRAINT fk_gerente_usuario
    FOREIGN KEY (usuario_id)
    REFERENCES Usuarios (usuario_id)
    ON DELETE CASCADE,
  CONSTRAINT chk_gerente_estatus CHECK (estatus IN ('activo', 'vacaciones', 'inactivo'))
);

-- -----------------------------------------------------
-- Tabla: Salones
-- -----------------------------------------------------
CREATE TABLE Salones (
  salon_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(150) NOT NULL,
  direccion CLOB,
  costo_renta NUMBER(10, 2) NOT NULL,
  capacidad_maxima NUMBER NOT NULL
);

-- -----------------------------------------------------
-- Tabla: Platillos
-- -----------------------------------------------------
CREATE TABLE Platillos (
  platillo_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(150) NOT NULL,
  descripcion CLOB,
  precio_por_persona NUMBER(10, 2) NOT NULL,
  tipo VARCHAR2(30) NOT NULL,
  instrucciones_preparacion CLOB,
  CONSTRAINT chk_platillo_tipo CHECK (tipo IN ('entrada', 'plato_fuerte', 'postre', 'bebida', 'complemento', 'vegetariano', 'bajo_en_calorias'))
);

-- -----------------------------------------------------
-- Tabla: Ingredientes
-- -----------------------------------------------------
CREATE TABLE Ingredientes (
  ingrediente_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100) NOT NULL UNIQUE,
  unidad_medida_almacen VARCHAR2(20) NOT NULL
);

-- -----------------------------------------------------
-- Tabla: Recetas (Platillo_Ingredientes)
-- -----------------------------------------------------
CREATE TABLE Recetas (
  receta_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  platillo_id NUMBER NOT NULL,
  ingrediente_id NUMBER NOT NULL,
  cantidad_por_porcion NUMBER(10, 3) NOT NULL,
  unidad_receta VARCHAR2(20) NOT NULL,
  CONSTRAINT fk_receta_platillo
    FOREIGN KEY (platillo_id)
    REFERENCES Platillos (platillo_id)
    ON DELETE CASCADE,
  CONSTRAINT fk_receta_ingrediente
    FOREIGN KEY (ingrediente_id)
    REFERENCES Ingredientes (ingrediente_id),
  CONSTRAINT uk_platillo_ingrediente UNIQUE (platillo_id, ingrediente_id)
);

-- -----------------------------------------------------
-- Tabla: Solicitudes
-- -----------------------------------------------------
CREATE TABLE Solicitudes (
  solicitud_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nombre_cliente VARCHAR2(200) NOT NULL,
  email_cliente VARCHAR2(100) NOT NULL,
  telefono_cliente VARCHAR2(20),
  fecha_evento_deseada DATE,
  numero_invitados_estimado NUMBER,
  detalles_solicitud CLOB,
  estatus VARCHAR2(30) DEFAULT 'pendiente' NOT NULL,
  gerente_asignado_id NUMBER,
  fecha_solicitud TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_solicitud_gerente
    FOREIGN KEY (gerente_asignado_id)
    REFERENCES Gerentes (gerente_id)
    ON DELETE SET NULL,
  CONSTRAINT chk_solicitud_estatus CHECK (estatus IN ('pendiente', 'contactado', 'descartado', 'convertido_proyecto'))
);

-- -----------------------------------------------------
-- Tabla: Proyectos (Eventos)
-- -----------------------------------------------------
CREATE TABLE Proyectos (
  proyecto_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  cliente_id NUMBER NOT NULL,
  gerente_id NUMBER NOT NULL,
  salon_id NUMBER NOT NULL,
  nombre_evento VARCHAR2(255),
  fecha_evento TIMESTAMP NOT NULL,
  numero_invitados NUMBER NOT NULL,
  estatus VARCHAR2(20) DEFAULT 'confirmado' NOT NULL,
  costo_total_calculado NUMBER(12, 2),
  fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_proyecto_cliente
    FOREIGN KEY (cliente_id)
    REFERENCES Clientes (cliente_id),
  CONSTRAINT fk_proyecto_gerente
    FOREIGN KEY (gerente_id)
    REFERENCES Gerentes (gerente_id),
  CONSTRAINT fk_proyecto_salon
    FOREIGN KEY (salon_id)
    REFERENCES Salones (salon_id),
  CONSTRAINT chk_proyecto_estatus CHECK (estatus IN ('confirmado', 'realizado', 'cancelado'))
);

-- -----------------------------------------------------
-- Tabla: Proyecto_Platillos
-- -----------------------------------------------------
CREATE TABLE Proyecto_Platillos (
  proyecto_platillo_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  proyecto_id NUMBER NOT NULL,
  platillo_id NUMBER NOT NULL,
  CONSTRAINT fk_pp_proyecto
    FOREIGN KEY (proyecto_id)
    REFERENCES Proyectos (proyecto_id)
    ON DELETE CASCADE,
  CONSTRAINT fk_pp_platillo
    FOREIGN KEY (platillo_id)
    REFERENCES Platillos (platillo_id),
  CONSTRAINT uk_proyecto_platillo UNIQUE (proyecto_id, platillo_id)
);

-- -----------------------------------------------------
-- Tabla: Transacciones_Pago
-- -----------------------------------------------------
CREATE TABLE Transacciones_Pago (
  pago_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  proyecto_id NUMBER NOT NULL,
  monto NUMBER(10, 2) NOT NULL,
  fecha_pago TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  tipo_pago VARCHAR2(20) NOT NULL,
  metodo_pago VARCHAR2(50),
  CONSTRAINT fk_pago_proyecto
    FOREIGN KEY (proyecto_id)
    REFERENCES Proyectos (proyecto_id)
    ON DELETE CASCADE,
  CONSTRAINT chk_tipo_pago CHECK (tipo_pago IN ('anticipo', 'pago_final', 'abono'))
);

-- Admin
INSERT INTO Usuarios (email, password_hash, tipo_usuario, nombre, apellido, telefono)
VALUES ('admin@catering.com', 'hash_admin', 'admin_gerente', 'Catherine', 'Dueña', '555-0001');

INSERT INTO Gerentes (usuario_id, estatus)
SELECT usuario_id, 'activo' FROM Usuarios WHERE email = 'admin@catering.com';

-- Gerentes
INSERT INTO Usuarios (email, password_hash, tipo_usuario, nombre, apellido, telefono)
VALUES ('gerente1@catering.com', 'hash_g1', 'gerente', 'Ana', 'Torres', '555-0002');
INSERT INTO Gerentes (usuario_id, estatus)
SELECT usuario_id, 'activo' FROM Usuarios WHERE email = 'gerente1@catering.com';

INSERT INTO Usuarios (email, password_hash, tipo_usuario, nombre, apellido, telefono)
VALUES ('gerente2@catering.com', 'hash_g2', 'gerente', 'Luis', 'Mora', '555-0003');
INSERT INTO Gerentes (usuario_id, estatus)
SELECT usuario_id, 'activo' FROM Usuarios WHERE email = 'gerente2@catering.com';

INSERT INTO Usuarios (email, password_hash, tipo_usuario, nombre, apellido, telefono)
VALUES ('gerente3_inactivo@catering.com', 'hash_g3', 'gerente', 'Pedro', 'Páramo', '555-0004');
INSERT INTO Gerentes (usuario_id, estatus)
SELECT usuario_id, 'inactivo' FROM Usuarios WHERE email = 'gerente3_inactivo@catering.com';

-- Clientes
INSERT INTO Usuarios (email, password_hash, tipo_usuario, nombre, apellido, telefono) VALUES ('cliente1@mail.com', 'hash_c1', 'cliente', 'Carlos', 'Sanchez', '555-1001');
INSERT INTO Clientes (usuario_id, direccion_facturacion) SELECT usuario_id, 'Fact. Calle 123' FROM Usuarios WHERE email = 'cliente1@mail.com';

INSERT INTO Usuarios (email, password_hash, tipo_usuario, nombre, apellido, telefono) VALUES ('cliente2@mail.com', 'hash_c2', 'cliente', 'Brenda', 'Gomez', '555-1002');
INSERT INTO Clientes (usuario_id, direccion_facturacion) SELECT usuario_id, 'Fact. Av. Siempre Viva 456' FROM Usuarios WHERE email = 'cliente2@mail.com';

INSERT INTO Usuarios (email, password_hash, tipo_usuario, nombre, apellido, telefono) VALUES ('cliente3@mail.com', 'hash_c3', 'cliente', 'Empresa', 'XYZ', '555-1003');
INSERT INTO Clientes (usuario_id, direccion_facturacion) SELECT usuario_id, 'Fact. Corporativo 789' FROM Usuarios WHERE email = 'cliente3@mail.com';

INSERT INTO Usuarios (email, password_hash, tipo_usuario, nombre, apellido, telefono) VALUES ('cliente4@mail.com', 'hash_c4', 'cliente', 'Familia', 'Perez', '555-1004');
INSERT INTO Clientes (usuario_id, direccion_facturacion) SELECT usuario_id, 'Fact. Calle Falsa 123' FROM Usuarios WHERE email = 'cliente4@mail.com';

INSERT INTO Usuarios (email, password_hash, tipo_usuario, nombre, apellido, telefono) VALUES ('cliente5@mail.com', 'hash_c5', 'cliente', 'Juan', 'Lopez', '555-1005');
INSERT INTO Clientes (usuario_id, direccion_facturacion) SELECT usuario_id, 'Fact. Blvd. Principal 321' FROM Usuarios WHERE email = 'cliente5@mail.com';

-- -----------------------------------------------------
-- 2. Salones
-- -----------------------------------------------------
INSERT INTO Salones (nombre, direccion, costo_renta, capacidad_maxima) VALUES ('Salón Imperial', 'Av. Reforma 100', 50000.00, 300);
INSERT INTO Salones (nombre, direccion, costo_renta, capacidad_maxima) VALUES ('Jardín Las Fuentes', 'Carretera al Sur Km 10', 35000.00, 150);
INSERT INTO Salones (nombre, direccion, costo_renta, capacidad_maxima) VALUES ('Terraza Bellavista', 'Centro Histórico 50', 20000.00, 80);
INSERT INTO Salones (nombre, direccion, costo_renta, capacidad_maxima) VALUES ('Centro de Convenciones Ágora', 'Zona Industrial 1', 100000.00, 1000);

-- -----------------------------------------------------
-- 3. Platillos e Ingredientes
-- -----------------------------------------------------
INSERT INTO Platillos (nombre, descripcion, precio_por_persona, tipo, instrucciones_preparacion) VALUES ('Crema de Champiñones', 'Suave crema...', 80.00, 'entrada', 'Licuar...');
INSERT INTO Platillos (nombre, descripcion, precio_por_persona, tipo, instrucciones_preparacion) VALUES ('Filete Mignon', 'Filete de res...', 250.00, 'plato_fuerte', 'Sellar...');
INSERT INTO Platillos (nombre, descripcion, precio_por_persona, tipo, instrucciones_preparacion) VALUES ('Salmón a la Naranja', 'Lomo de salmón...', 220.00, 'plato_fuerte', 'Hornear...');
INSERT INTO Platillos (nombre, descripcion, precio_por_persona, tipo, instrucciones_preparacion) VALUES ('Ensalada César', 'Lechuga...', 90.00, 'entrada', 'Mezclar...');
INSERT INTO Platillos (nombre, descripcion, precio_por_persona, tipo, instrucciones_preparacion) VALUES ('Tiramisú', 'Postre italiano...', 110.00, 'postre', 'Capas...');
INSERT INTO Platillos (nombre, descripcion, precio_por_persona, tipo, instrucciones_preparacion) VALUES ('Ensalada Caprese (Veg)', 'Tomate...', 100.00, 'vegetariano', 'Cortar...');
INSERT INTO Platillos (nombre, descripcion, precio_por_persona, tipo, instrucciones_preparacion) VALUES ('Agua de Jamaica', 'Agua fresca...', 30.00, 'bebida', 'Hervir...');
INSERT INTO Platillos (nombre, descripcion, precio_por_persona, tipo, instrucciones_preparacion) VALUES ('Pechuga a la Plancha', 'Pechuga...', 150.00, 'bajo_en_calorias', 'Sazonar...');

INSERT INTO Ingredientes (nombre, unidad_medida_almacen) VALUES ('Champiñón', 'kg');
INSERT INTO Ingredientes (nombre, unidad_medida_almacen) VALUES ('Crema Lyncott', 'litro');
INSERT INTO Ingredientes (nombre, unidad_medida_almacen) VALUES ('Filete de Res', 'kg');
INSERT INTO Ingredientes (nombre, unidad_medida_almacen) VALUES ('Vino Tinto', 'litro');
INSERT INTO Ingredientes (nombre, unidad_medida_almacen) VALUES ('Lomo de Salmón', 'kg');
INSERT INTO Ingredientes (nombre, unidad_medida_almacen) VALUES ('Naranja', 'kg');
INSERT INTO Ingredientes (nombre, unidad_medida_almacen) VALUES ('Pechuga de Pollo', 'kg');

-- Recetas (Usando subconsultas para obtener IDs)
INSERT INTO Recetas (platillo_id, ingrediente_id, cantidad_por_porcion, unidad_receta)
SELECT p.platillo_id, i.ingrediente_id, 0.150, 'kg' FROM Platillos p, Ingredientes i WHERE p.nombre = 'Crema de Champiñones' AND i.nombre = 'Champiñón';

INSERT INTO Recetas (platillo_id, ingrediente_id, cantidad_por_porcion, unidad_receta)
SELECT p.platillo_id, i.ingrediente_id, 0.050, 'litro' FROM Platillos p, Ingredientes i WHERE p.nombre = 'Crema de Champiñones' AND i.nombre = 'Crema Lyncott';

INSERT INTO Recetas (platillo_id, ingrediente_id, cantidad_por_porcion, unidad_receta)
SELECT p.platillo_id, i.ingrediente_id, 0.250, 'kg' FROM Platillos p, Ingredientes i WHERE p.nombre = 'Filete Mignon' AND i.nombre = 'Filete de Res';

INSERT INTO Recetas (platillo_id, ingrediente_id, cantidad_por_porcion, unidad_receta)
SELECT p.platillo_id, i.ingrediente_id, 0.200, 'kg' FROM Platillos p, Ingredientes i WHERE p.nombre LIKE 'Pechuga%' AND i.nombre = 'Pechuga de Pollo';

-- -----------------------------------------------------
-- 4. Proyectos (Eventos)
-- -----------------------------------------------------
-- Helper para obtener IDs (En Oracle puro SQL script es mejor hacerlo directo si se conocen los datos o con subconsultas)

-- Proyecto 1: Realizado
INSERT INTO Proyectos (cliente_id, gerente_id, salon_id, nombre_evento, fecha_evento, numero_invitados, estatus)
SELECT 
    c.cliente_id, 
    g.gerente_id, 
    s.salon_id, 
    'Boda Sanchez', 
    TIMESTAMP '2024-05-10 18:00:00', 
    250, 
    'realizado'
FROM Clientes c 
JOIN Usuarios uc ON c.usuario_id = uc.usuario_id
CROSS JOIN Gerentes g                            -- CORRECCIÓN: Cambiado JOIN por CROSS JOIN
JOIN Usuarios ug ON g.usuario_id = ug.usuario_id -- Se mantiene el JOIN para validar el usuario del gerente
CROSS JOIN Salones s
WHERE uc.email = 'cliente1@mail.com' 
  AND ug.email = 'gerente1@catering.com' 
  AND s.nombre = 'Salón Imperial';

-- Proyecto 2: Realizado
INSERT INTO Proyectos (cliente_id, gerente_id, salon_id, nombre_evento, fecha_evento, numero_invitados, estatus)
SELECT 
    c.cliente_id, 
    g.gerente_id, 
    s.salon_id, 
    'XV Años Brenda', 
    TIMESTAMP '2024-06-15 14:00:00', 
    100, 
    'realizado'
FROM Clientes c 
JOIN Usuarios uc ON c.usuario_id = uc.usuario_id -- Une Cliente con su Usuario
CROSS JOIN Gerentes g                            -- CAMBIO: Usamos CROSS JOIN aquí
JOIN Usuarios ug ON g.usuario_id = ug.usuario_id -- Une Gerente con su Usuario
CROSS JOIN Salones s                             -- Une el resultado anterior con Salones
WHERE uc.email = 'cliente2@mail.com' 
  AND ug.email = 'gerente2@catering.com' 
  AND s.nombre = 'Jardín Las Fuentes';

-- Proyecto 3: Activo (Futuro)
INSERT INTO Proyectos (cliente_id, gerente_id, salon_id, nombre_evento, fecha_evento, numero_invitados, estatus)
SELECT 
    c.cliente_id, 
    g.gerente_id, 
    s.salon_id, 
    'Boda Civil', 
    TIMESTAMP '2025-12-12 18:00:00', 
    100, 
    'confirmado'
FROM Clientes c 
JOIN Usuarios uc ON c.usuario_id = uc.usuario_id
CROSS JOIN Gerentes g                     
JOIN Usuarios ug ON g.usuario_id = ug.usuario_id 
CROSS JOIN Salones s
WHERE uc.email = 'cliente1@mail.com' 
  AND ug.email = 'gerente1@catering.com' 
  AND s.nombre = 'Jardín Las Fuentes';

-- Proyecto 4: Activo (Cercano, no pagado)
INSERT INTO Proyectos (cliente_id, gerente_id, salon_id, nombre_evento, fecha_evento, numero_invitados, estatus)
SELECT 
    c.cliente_id, 
    g.gerente_id, 
    s.salon_id, 
    'Cena de Fin de Año XYZ', 
    TIMESTAMP '2025-11-19 20:00:00', 
    75, 
    'confirmado'
FROM Clientes c 
JOIN Usuarios uc ON c.usuario_id = uc.usuario_id
CROSS JOIN Gerentes g                            -- CORRECCIÓN AQUÍ
JOIN Usuarios ug ON g.usuario_id = ug.usuario_id 
CROSS JOIN Salones s
WHERE uc.email = 'cliente3@mail.com' 
  AND ug.email = 'gerente2@catering.com' 
  AND s.nombre = 'Terraza Bellavista';

-- Relacionar platillos a proyectos (Ejemplo para el Proyecto 1 - Boda Sanchez)
INSERT INTO Proyecto_Platillos (proyecto_id, platillo_id)
SELECT p.proyecto_id, pl.platillo_id
FROM Proyectos p, Platillos pl
WHERE p.nombre_evento = 'Boda Sanchez' AND pl.nombre IN ('Crema de Champiñones', 'Filete Mignon', 'Tiramisú');

-- Relacionar platillos a proyectos (Ejemplo para el Proyecto 3 - Boda Civil)
INSERT INTO Proyecto_Platillos (proyecto_id, platillo_id)
SELECT p.proyecto_id, pl.platillo_id
FROM Proyectos p, Platillos pl
WHERE p.nombre_evento = 'Boda Civil' AND pl.nombre IN ('Ensalada Caprese (Veg)', 'Salmón a la Naranja');

-- Pagos (Transacciones)
INSERT INTO Transacciones_Pago (proyecto_id, monto, tipo_pago)
SELECT proyecto_id, 20000.00, 'anticipo'
FROM Proyectos WHERE nombre_evento = 'Boda Civil';

COMMIT;

------
SELECT
  ing.nombre AS ingrediente,
  SUM(pro.numero_invitados * rec.cantidad_por_porcion) AS cantidad_total_necesaria,
  rec.unidad_receta AS unidad
FROM Proyectos pro
JOIN Proyecto_Platillos pp ON pro.proyecto_id = pp.proyecto_id
JOIN Recetas rec ON pp.platillo_id = rec.platillo_id
JOIN Ingredientes ing ON rec.ingrediente_id = ing.ingrediente_id
WHERE
  pro.estatus = 'confirmado' 
  AND pro.fecha_evento BETWEEN TO_TIMESTAMP('2025-11-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS') 
                           AND TO_TIMESTAMP('2025-11-23 23:59:59', 'YYYY-MM-DD HH24:MI:SS')
GROUP BY
  ing.ingrediente_id, 
  ing.nombre, 
  rec.unidad_receta
ORDER BY
  ing.nombre;
-- -----------------------------------------------------
-- Reporte 5: Eventos no finiquitados (Próximas 3 semanas)
-- -----------------------------------------------------
SELECT
  pro.proyecto_id,
  pro.nombre_evento,
  pro.fecha_evento,
  u.nombre || ' ' || u.apellido AS cliente_nombre,
  u.telefono AS cliente_telefono,
  u.email AS cliente_email,
  gu.nombre || ' ' || gu.apellido AS gerente_nombre,
  -- CORRECCIÓN AQUÍ: Usamos CAST para convertir el Timestamp a Date
  TRUNC(CAST(pro.fecha_evento AS DATE) - TO_DATE('2025-11-17', 'YYYY-MM-DD')) AS dias_faltantes
FROM Proyectos pro
JOIN Clientes c ON pro.cliente_id = c.cliente_id
JOIN Usuarios u ON c.usuario_id = u.usuario_id
JOIN Gerentes g ON pro.gerente_id = g.gerente_id
JOIN Usuarios gu ON g.usuario_id = gu.usuario_id
WHERE
  pro.estatus = 'confirmado'
  AND pro.fecha_evento BETWEEN TO_DATE('2025-11-17', 'YYYY-MM-DD') 
                           AND (TO_DATE('2025-11-17', 'YYYY-MM-DD') + 21)
ORDER BY
  pro.fecha_evento ASC;

-- -----------------------------------------------------
-- Reporte 7: Platillos más populares
-- -----------------------------------------------------
SELECT
  p.nombre AS platillo,
  p.tipo,
  COUNT(pp.platillo_id) AS total_veces_pedido
FROM Platillos p
JOIN Proyecto_Platillos pp ON p.platillo_id = pp.platillo_id
JOIN Proyectos pro ON pp.proyecto_id = pro.proyecto_id
WHERE
  pro.estatus IN ('realizado', 'confirmado')
GROUP BY
  p.platillo_id, p.nombre, p.tipo
ORDER BY
  total_veces_pedido DESC;

-- -----------------------------------------------------
-- Reporte 7 (B): Platillo MENOS demandado (Top 5)
-- -----------------------------------------------------
SELECT
  p.nombre AS platillo,
  p.tipo,
  COUNT(pp.platillo_id) AS total_veces_pedido
FROM Platillos p
LEFT JOIN Proyecto_Platillos pp ON p.platillo_id = pp.platillo_id
LEFT JOIN Proyectos pro ON pp.proyecto_id = pro.proyecto_id AND pro.estatus IN ('realizado', 'confirmado')
GROUP BY
  p.platillo_id, p.nombre, p.tipo
ORDER BY
  total_veces_pedido ASC
FETCH FIRST 5 ROWS ONLY;

select * from clientes;
select * from usuarios;